=== OI4/oi4-oec-registry/OI4-Service/src/Application/ConformityValidator/Schemas/mam.schema.json
{
  "$id": "mam.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "description": "A representation of an event",
  "properties": {
    "Description": {
      "$ref": "LocalizedText.schema.json"
    },
    "DeviceClass": {
      "type": "string",
      "description": ""
    },
    "DeviceManual": {
      "type": "string",
      "description": ""
    },
    "DeviceRevision": {
      "type": "string",
      "description": ""
    },
    "HardwareRevision": {
      "type": "string",
      "description": ""
    },
    "Manufacturer": {
      "$ref": "LocalizedText.schema.json" 
    },
    "ManufacturerUri": {
      "type": "string",
      "format": "uri",
      "description": "Manufacturer URI"
    },
    "Model": {
      "$ref": "LocalizedText.schema.json"
    },
    "ProductCode": {
      "type": "string",
      "description": ""
    },
    "ProductInstanceUri": {
      "$ref": "oi4Identifier.schema.json"
    },
    "RevisionCounter": {
      "type": "integer",
      "description": "",
      "minimum": 0
    },
    "SerialNumber": {
      "type": "string",
      "description": ""
    },
    "SoftwareRevision": {
      "type": "string",
      "description": ""
    }
  },
  "required": [
    "Description",
    "DeviceClass",
    "DeviceManual",
    "DeviceRevision",
    "HardwareRevision",
    "Manufacturer",
    "ManufacturerUri",
    "Model",
    "ProductCode",
    "ProductInstanceUri",
    "RevisionCounter",
    "SerialNumber",
    "SoftwareRevision"
  ],
  "type": "object"
}

=== OI4/oi4-oec-registry/packages/oi4-registry-service/src/Application/Resources/mam.json
{
  "Manufacturer":{"Locale":"en-US","Text":"Open Industry 4.0 Alliance Community"},
  "ManufacturerUri":"openindustry4.com",
  "Model":{"Locale":"en-US","Text":"OEC Registry"},
  "ProductCode":"OEC-REG",
  "HardwareRevision":"",
  "SoftwareRevision":"1.1.0.0",
  "DeviceRevision":"1.1.0.0",
  "DeviceManual":"https://openindustry4.com/fileadmin/Dateien/Downloads/2019_11_20_OI4_Whitepaper_General.pdf",
  "DeviceClass":"OI4.Registry",
  "SerialNumber":"OEC-Registry",
  "ProductInstanceUri":"oi4/appid/service",
  "RevisionCounter":0,
  "Description":
  {
    "Locale":"en-US",
    "Text":"The OEC Registry, an Open Industry 4.0 Alliance application"
  }
}

=== OI4/oi4-oec-registry/docker_configs/config/mam.json
{
  "Manufacturer":{"Locale":"en-US","Text":"ACME Corporation"},
  "ManufacturerUri":"acme.com",
  "Model":{"Locale":"en-US","Text":"OEC Utility"},
  "ProductCode":"OEC-ACME-Registry",
  "HardwareRevision":"",
  "SoftwareRevision":"1.1",
  "DeviceRevision":"1",
  "DeviceManual":"1.0",
  "DeviceClass":"Oi4.Registry",
  "SerialNumber":"F12AB34",
  "ProductInstanceUri":"oi4/appid/service",
  "RevisionCounter":0,
  "Description":
  {
    "Locale":"en-US",
    "Text":"An OI4 OEC Registry, provided by the OI4 community"
  }
}
