=== OI4/oi4-oec-registry/OI4-Service/src/Application/ConformityValidator/Schemas/NetworkMessage.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A representation of an event",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "CorrelationId": {
      "type": "string",
      "description": "Correlation ID used for logging and as debug information"
    },
    "DataSetClassId": {
      "type": "string",
      "description": "Dataset Class ID"
    },
    "MessageId": {
      "type": "string",
      "description": "Message ID"
    },
    "Messages": {
      "type": "array",
      "description": "Messages Array",
      "items": {
        "$ref": "DataSetMessage.schema.json"
      }
    },
    "MessageType": {
      "type": "string",
      "enum": [
        "ua-data"
      ],
      "description": "Message Type"
    },
    "PublisherId": {
      "type": "string",
      "description": "Publisher ID"
    }
  },
  "required": [
    "MessageId",
    "MessageType",
    "PublisherId",
    "DataSetClassId",
    "Messages"
  ]
}

=== OI4/oi4-oec-registry/OI4-Service/src/Config/hostData.json
{
        "MessageId": "not yet defined",
        "MessageType": "ua-data",
        "PublisherId": "Registry/hilscher.com/container/99/FFEF3342",
        "DataSetClassId": "cd8d179a-fd2d-4ad4-ac6b-b0801722a4b6",
        "Messages": [
            {
                "DataSetWriterId": "BaseOI4Container",
                "SequenceNumber": 2,
                "MetaDataVersion": {
                    "majorVersion": 601689600,
                    "minorVersion": 614822400
                },
                "Timestamp": "2019-06-26T13:16:00+01:00",
                "Status": 2147942400,
                "Payload": {
                    "CPULoad": 37,
                    "FreeMemory": 400 
                }
            }
        ]
}

=== OI4/oi4-oec-registry/OI4-Service/src/Config/weatherData.json
{
    "MessageId": "not yet defined",
    "MessageType": "ua-data",
    "PublisherId": "Registry/hilscher.com/container/99/FFEF3342",
    "DataSetClassId": "da508b5b-5ebc-439a-818f-d723a79afafc",
    "Messages": [
        {
            "DataSetWriterId": "BaseOI4Container",
            "SequenceNumber": 2,
            "MetaDataVersion": {
                "majorVersion": 601689600,
                "minorVersion": 614822400
            },
            "Timestamp": "2019-06-26T13:16:00+01:00",
            "Status": 2147942400,
            "Payload": {
                "Temperature": 37,
                "Humidity": 50
            }
        }
    ]
}
